AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to deploy API Gateway through infrastructure as code.
Parameters:
  LambdaFunctionName:
    ConstraintDescription: must contain only alphanumeric characters.
    Default: CustomerServerless
    Description: The name of the Lambda function.
    MaxLength: 64
    MinLength: 1
    Type: String

  LambdaFunctionArn:
    Description: Lambda function Arn.
    Type: String

Resources:

  APIGatewayRest:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Join ["",[!Ref LambdaFunctionName, "APIGateway"]]
      Description: !Join ["",["API Gateway to Lambda Function ",!Ref LambdaFunctionName]]
      EndpointConfiguration:
        Types:
          - REGIONAL

  APIGatewayResourceCustomer:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref APIGatewayRest
      ParentId: !GetAtt APIGatewayRest.RootResourceId
      PathPart: customer

  APIGatewayCustomerPOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      OperationName: !Sub ${AWS::AccountId}
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref APIGatewayResourceCustomer
      RestApiId: !Ref APIGatewayRest
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join ["",["arn:aws:apigateway:",!Ref "AWS::Region", ":lambda:path/2015-03-31/functions/", !Ref LambdaFunctionArn,"/invocations"]]
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates: {"application/json":""}
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "application/json": "Empty" }

  APIGatewayRestPermissionCustomerPost:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGatewayRest}/*/POST/customer"
      FunctionName: !Ref LambdaFunctionArn
    DependsOn:
    - APIGatewayRest
    - APIGatewayCustomerPOSTMethod

  APIGatewayCustomerPUTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      OperationName: !Sub ${AWS::AccountId}
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: PUT
      ResourceId: !Ref APIGatewayResourceCustomer
      RestApiId: !Ref APIGatewayRest
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join ["",["arn:aws:apigateway:",!Ref "AWS::Region", ":lambda:path/2015-03-31/functions/", !Ref LambdaFunctionArn,"/invocations"]]
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates: {"application/json":""}
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "application/json": "Empty" }

  APIGatewayRestPermissionCustomerPut:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGatewayRest}/*/PUT/customer"
      FunctionName: !Ref LambdaFunctionArn
    DependsOn:
    - APIGatewayRest
    - APIGatewayCustomerPUTMethod

  APIGatewayResourceCustomerKey:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref APIGatewayRest
      ParentId: !Ref APIGatewayResourceCustomer
      PathPart: "{key}"

  APIGatewayCustomerKeyGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      OperationName: !Sub ${AWS::AccountId}
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref APIGatewayResourceCustomerKey
      RestApiId: !Ref APIGatewayRest
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join ["",["arn:aws:apigateway:",!Ref "AWS::Region", ":lambda:path/2015-03-31/functions/", !Ref LambdaFunctionArn,"/invocations"]]
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates: {"application/json":""}
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "application/json": "Empty" }

  APIGatewayRestPermissionCustomerKeyGet:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGatewayRest}/*/GET/customer/*"
      FunctionName: !Ref LambdaFunctionArn
    DependsOn:
    - APIGatewayRest
    - APIGatewayCustomerKeyGetMethod

  APIGatewayCustomerKeyDeleteMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      OperationName: !Sub ${AWS::AccountId}
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: DELETE
      ResourceId: !Ref APIGatewayResourceCustomerKey
      RestApiId: !Ref APIGatewayRest
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join ["",["arn:aws:apigateway:",!Ref "AWS::Region", ":lambda:path/2015-03-31/functions/", !Ref LambdaFunctionArn,"/invocations"]]
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates: {"application/json":""}
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "application/json": "Empty" }

  APIGatewayRestPermissionCustomerKeyDelete:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGatewayRest}/*/DELETE/customer/*"
      FunctionName: !Ref LambdaFunctionArn
    DependsOn:
    - APIGatewayRest
    - APIGatewayCustomerKeyDeleteMethod

  APIGatewayResourceCustomerAll:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref APIGatewayRest
      ParentId: !Ref APIGatewayResourceCustomer
      PathPart: "all"

  APIGatewayCustomerAllGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      OperationName: !Sub ${AWS::AccountId}
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref APIGatewayResourceCustomerAll
      RestApiId: !Ref APIGatewayRest
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join ["",["arn:aws:apigateway:",!Ref "AWS::Region", ":lambda:path/2015-03-31/functions/", !Ref LambdaFunctionArn,"/invocations"]]
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates: {"application/json":""}
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "application/json": "Empty" }

  APIGatewayRestPermissionCustomerAllGet:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGatewayRest}/*/GET/customer/all"
      FunctionName: !Ref LambdaFunctionArn
    DependsOn:
    - APIGatewayRest
    - APIGatewayCustomerAllGetMethod

  APIGatewayModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: 'application/json'
      RestApiId: !Ref APIGatewayRest
      Schema: {}

  APIGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref APIGatewayRest
      Description: Lambda API Delployment
    DependsOn: APIGatewayCustomerKeyGetMethod

  APIGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref APIGatewayDeployment
      RestApiId: !Ref APIGatewayRest
      StageName: ist
      Description: API Gateway IST stage
    DependsOn: APIGatewayDeployment